In [1]:
from database.rds_crypto_market_db_util import RdsCryptoMarketDbUtil
import pandas as pd
from storage.s3_storage import S3Storage
from config.config import AWSConf
from models.coin_market_snapshots import CoinMarketSnapshots

In [2]:
rds_crypto_market_db_util = RdsCryptoMarketDbUtil()

storage = S3Storage(
            bucket_name=AWSConf.S3_RAW_STORAGE_BUCKET_NAME,
            profile_name=AWSConf.AWS_PROFILE_NAME,
        )

recent_object_by_hour = storage.get_latest_object_for_hour(year=2026, month=8, day=20, hour=10)

data_obj = storage.get_json_object(object_key=recent_object_by_hour['Key'])
snapshot_datetime = data_obj['snapshot_datetime']
sn_df = pd.DataFrame(data_obj['data'])
sn_df['snapshot_datetime'] = snapshot_datetime

In [3]:
sn_df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated,snapshot_datetime
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,71835.000000,1441565495522,1,1441565495522,63803374774,71954.000000,...,2.100000e+07,126080.000000,-43.02412,2025-10-06T10:57:42.000Z,67.810000,1.058374e+05,2013-07-05T16:00:00.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2285.070000,275702787194,2,275702787194,36123948668,2318.660000,...,NaN,4946.050000,-53.80014,2025-08-24T11:21:03.000Z,0.432979,5.276549e+05,2015-10-19T16:00:00.000Z,"{'times': 41.50669957440995, 'currency': 'btc'...",2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999276,182971534127,3,188434647831,102425300978,0.999840,...,NaN,1.320000,-24.47435,2018-07-23T16:00:00.000Z,0.572521,7.453969e+01,2015-03-01T16:00:00.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,642.980000,85600181377,4,85600184353,1729636397,643.960000,...,2.000000e+08,1369.990000,-53.06691,2025-10-13T00:41:24.000Z,0.039818,1.614708e+06,2017-10-18T16:00:00.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.160000,72609944720,5,115831295825,3856367587,1.160000,...,1.000000e+11,3.650000,-68.21705,2025-07-17T19:40:53.000Z,0.002686,4.304360e+04,2014-05-21T16:00:00.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
5,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999538,72380284816,6,72382531951,26168238833,1.000000,...,NaN,1.043000,-4.20970,2018-11-14T16:00:00.000Z,0.877647,1.388842e+01,2023-03-11T00:02:13.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
6,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,87.220000,50835589053,7,55152432872,5610964737,87.830000,...,NaN,293.310000,-70.26415,2025-01-19T03:15:27.000Z,0.500801,1.731585e+04,2020-05-11T11:35:23.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
7,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,0.077242,12009759189,11,13222666174,1104411595,0.077189,...,NaN,0.731578,-89.44172,2021-05-07T21:08:23.000Z,0.000087,8.878235e+04,2015-05-05T16:00:00.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
8,cardano,ada,Cardano,https://coin-images.coingecko.com/coins/images...,0.190128,7121574687,18,8549059674,578753153,0.191823,...,4.500000e+10,3.090000,-93.84084,2021-09-01T22:00:10.000Z,0.019253,8.875360e+02,2020-03-12T18:22:55.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00
9,avalanche-2,avax,Avalanche,https://coin-images.coingecko.com/coins/images...,6.920000,2985386093,30,3204354667,399542752,6.930000,...,7.200000e+08,144.960000,-95.22976,2021-11-21T06:18:56.000Z,2.800000,1.468704e+02,2020-12-31T05:15:21.000Z,None,2026-08-20T10:37:30.000Z,2026-08-20T10:40:47.668140+00:00

In [4]:
query = "select coin_id, api_coin_id from coins"

coins_df = rds_crypto_market_db_util.fetchall_df(query)

/Users/adelement/Developer/data_eng_project/crypto-data-engineering/database/database_util.py:212: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, self.conn)  # type: ignore

In [5]:
coins_df

   coin_id  api_coin_id
0       10  avalanche-2
1        4  binancecoin
2        1      bitcoin
3        9      cardano
4        8     dogecoin
5        2     ethereum
6        5       ripple
7        7       solana
8        3       tether
9        6     usd-coin

In [6]:
sn_df = sn_df.merge(coins_df, how='left', left_on='id', right_on='api_coin_id')

In [7]:
sn_df.columns

Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated', 'snapshot_datetime', 'coin_id', 'api_coin_id'],
      dtype='str')

In [8]:
report_df = sn_df[[
"coin_id",
"snapshot_datetime",
"current_price",
"market_cap",
"market_cap_rank",
"total_volume",
"high_24h",
"low_24h",
"price_change_24h",
"price_change_percentage_24h",
"market_cap_change_24h",
"market_cap_change_percentage_24h",
"circulating_supply",
"total_supply"]]

In [9]:
table_cols = ["coin_id",
"snapshot_datetime",
"current_price_usd",
"market_cap_usd",
"market_cap_rank",
"total_volume_usd",
"high_24h_usd",
"low_24h_usd",
"price_change_24h_usd",
"price_change_24h_pct",
"market_cap_change_24h_usd",
"market_cap_change_24h_pct",
"circulating_supply",
"total_supply"]

In [10]:
report_df.columns = table_cols

In [11]:
report_df

,coin_id,snapshot_datetime,current_price_usd,market_cap_usd,market_cap_rank,total_volume_usd,high_24h_usd,low_24h_usd,price_change_24h_usd,price_change_24h_pct,market_cap_change_24h_usd,market_cap_change_24h_pct,circulating_supply,total_supply
0,1,2026-08-20T10:40:47.668140+00:00,71835.000000,1441565495522,1,63803374774,71954.000000,64416.000000,7378.610000,11.4,147825547380,11.42622,2.007152e+07,2.007152e+07
1,2,2026-08-20T10:40:47.668140+00:00,2285.070000,275702787194,2,36123948668,2318.660000,1918.590000,363.410000,18.5,43793560545,18.88392,1.206817e+08,1.206817e+08
2,3,2026-08-20T10:40:47.668140+00:00,0.999276,182971534127,3,102425300978,0.999840,0.999172,-0.000013,0.0,14000641,0.00765,1.830999e+11,1.885668e+11
3,4,2026-08-20T10:40:47.668140+00:00,642.980000,85600181377,4,1729636397,643.960000,601.990000,40.380000,6.6,5356136350,6.67481,1.331634e+08,1.331634e+08
4,5,2026-08-20T10:40:47.668140+00:00,1.160000,72609944720,5,3856367587,1.160000,1.004000,0.154458,14.1,9652955865,15.33262,6.267694e+10,9.998563e+10
5,6,2026-08-20T10:40:47.668140+00:00,0.999538,72380284816,6,26168238833,1.000000,0.999136,-0.000149,0.0,600326066,0.83634,7.241371e+10,7.245893e+10
6,7,2026-08-20T10:40:47.668140+00:00,87.220000,50835589053,7,5610964737,87.830000,77.350000,9.760000,12.7,5675000531,12.56627,5.830062e+08,6.325137e+08
7,8,2026-08-20T10:40:47.668140+00:00,0.077242,12009759189,11,1104411595,0.077189,0.070022,0.007085,9.2,1096441898,10.04683,1.555695e+11,1.712818e+11
8,9,2026-08-20T10:40:47.668140+00:00,0.190128,7121574687,18,578753153,0.191823,0.173784,0.015278,8.2,567135034,8.65269,3.748609e+10,4.500000e+10
9,10,2026-08-20T10:40:47.668140+00:00,6.920000,2985386093,30,399542752,6.930000,6.300000,0.595349,7.8,256693843,9.40721,4.317720e+08,4.634411e+08

In [12]:
record_list = list(report_df.itertuples(index=False, name=None))

record_list

[(1,
  '2026-08-20T10:40:47.668140+00:00',
  71835.0,
  1441565495522,
  1,
  63803374774,
  71954.0,
  64416.0,
  7378.61,
  11.4,
  147825547380,
  11.42622,
  20071518.0,
  20071518.0),
 (2,
  '2026-08-20T10:40:47.668140+00:00',
  2285.07,
  275702787194,
  2,
  36123948668,
  2318.66,
  1918.59,
  363.41,
  18.5,
  43793560545,
  18.88392,
  120681739.9327726,
  120681739.9327726),
 (3,
  '2026-08-20T10:40:47.668140+00:00',
  0.999276,
  182971534127,
  3,
  102425300978,
  0.99984,
  0.999172,
  -1.306926278255e-05,
  0.0,
  14000641,
  0.00765,
  183099871086.6849,
  188566816640.5762),
 (4,
  '2026-08-20T10:40:47.668140+00:00',
  642.98,
  85600181377,
  4,
  1729636397,
  643.96,
  601.99,
  40.38,
  6.6,
  5356136350,
  6.67481,
  133163363.71,
  133163355.45),
 (5,
  '2026-08-20T10:40:47.668140+00:00',
  1.16,
  72609944720,
  5,
  3856367587,
  1.16,
  1.004,
  0.154458,
  14.1,
  9652955865,
  15.33262,
  62676938832.0,
  99985629672.0),
 (6,
  '2026-08-20T10:40:47.668140+00:00',
  0.999538,
  72380284816,
  6,
  26168238833,
  1.0,
  0.999136,
  -0.000149163022401089,
  0.0,
  600326066,
  0.83634,
  72413707761.82578,
  72458931134.5945),
 (7,
  '2026-08-20T10:40:47.668140+00:00',
  87.22,
  50835589053,
  7,
  5610964737,
  87.83,
  77.35,
  9.76,
  12.7,
  5675000531,
  12.56627,
  583006168.1018128,
  632513716.2318383),
 (8,
  '2026-08-20T10:40:47.668140+00:00',
  0.077242,
  12009759189,
  11,
  1104411595,
  0.077189,
  0.070022,
  0.00708543,
  9.2,
  1096441898,
  10.04683,
  155569466383.70526,
  171281793126.579),
 (9,
  '2026-08-20T10:40:47.668140+00:00',
  0.190128,
  7121574687,
  18,
  578753153,
  0.191823,
  0.173784,
  0.01527791,
  8.2,
  567135034,
  8.65269,
  37486094747.8024,
  45000000000.0),
 (10,
  '2026-08-20T10:40:47.668140+00:00',
  6.92,
  2985386093,
  30,
  399542752,
  6.93,
  6.3,
  0.595349,
  7.8,
  256693843,
  9.40721,
  431771961.1772119,
  463441061.1772119)]

In [13]:
CoinMarketSnapshots.insert_coin_market_snapshots_data(record_list, rds_crypto_market_db_util)

True